# Generated by Django 5.2 on 2026-01-15 18:05

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del trabajo o proyecto', max_length=255, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción detallada del trabajo realizado', verbose_name='Descripción')),
                ('image', models.ImageField(help_text='Imagen principal del trabajo', upload_to='trabajos/%Y/%m/', verbose_name='Imagen')),
                ('categoria', models.CharField(choices=[('diseno_grafico', 'Diseño Gráfico'), ('social_media', 'Social Media'), ('diseno_web', 'Diseño Web'), ('desarrollo_software', 'Desarrollo de Software'), ('estampado', 'Estampado'), ('impresiones', 'Impresiones'), ('branding', 'Branding'), ('packaging', 'Packaging'), ('otro', 'Otro')], default='otro', help_text='Categoría del trabajo', max_length=50, verbose_name='Categoría')),
                ('fecha_realizacion', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se realizó el trabajo', verbose_name='Fecha de Realización')),
                ('cliente', models.CharField(blank=True, help_text='Nombre del cliente (opcional)', max_length=255, verbose_name='Cliente')),
                ('destacado', models.BooleanField(default=False, help_text='Marcar si el trabajo debe aparecer destacado', verbose_name='Destacado')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (menor número = mayor prioridad)', verbose_name='Orden')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Trabajos',
                'ordering': ['orden', '-fecha_realizacion', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTrabajo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del trabajo o proyecto', max_length=255, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción detallada del trabajo realizado', verbose_name='Descripción')),
                ('image', models.TextField(help_text='Imagen principal del trabajo', max_length=100, verbose_name='Imagen')),
                ('categoria', models.CharField(choices=[('diseno_grafico', 'Diseño Gráfico'), ('social_media', 'Social Media'), ('diseno_web', 'Diseño Web'), ('desarrollo_software', 'Desarrollo de Software'), ('estampado', 'Estampado'), ('impresiones', 'Impresiones'), ('branding', 'Branding'), ('packaging', 'Packaging'), ('otro', 'Otro')], default='otro', help_text='Categoría del trabajo', max_length=50, verbose_name='Categoría')),
                ('fecha_realizacion', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se realizó el trabajo', verbose_name='Fecha de Realización')),
                ('cliente', models.CharField(blank=True, help_text='Nombre del cliente (opcional)', max_length=255, verbose_name='Cliente')),
                ('destacado', models.BooleanField(default=False, help_text='Marcar si el trabajo debe aparecer destacado', verbose_name='Destacado')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (menor número = mayor prioridad)', verbose_name='Orden')),
                ('creado_en', models.DateTimeField(blank=True, editable=False, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado en')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Trabajo',
                'verbose_name_plural': 'historical Trabajos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
