# Generated by Django 5.2 on 2026-01-28 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#06b6d4', max_length=7)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='historicaltrabajo',
            name='categoria',
            field=models.CharField(blank=True, choices=[('diseno_grafico', 'Diseño Gráfico'), ('social_media', 'Social Media'), ('diseno_web', 'Diseño Web'), ('desarrollo_software', 'Desarrollo de Software'), ('estampado', 'Estampado'), ('impresiones', 'Impresiones'), ('branding', 'Branding'), ('packaging', 'Packaging'), ('otro', 'Otro')], default='otro', help_text='Categoría del trabajo (Legacy)', max_length=50, verbose_name='Categoría (Legacy)'),
        ),
        migrations.AlterField(
            model_name='historicaltrabajo',
            name='image',
            field=models.TextField(blank=True, help_text='Imagen principal del trabajo (Legacy)', max_length=100, null=True, verbose_name='Imagen (Legacy)'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='categoria',
            field=models.CharField(blank=True, choices=[('diseno_grafico', 'Diseño Gráfico'), ('social_media', 'Social Media'), ('diseno_web', 'Diseño Web'), ('desarrollo_software', 'Desarrollo de Software'), ('estampado', 'Estampado'), ('impresiones', 'Impresiones'), ('branding', 'Branding'), ('packaging', 'Packaging'), ('otro', 'Otro')], default='otro', help_text='Categoría del trabajo (Legacy)', max_length=50, verbose_name='Categoría (Legacy)'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen principal del trabajo (Legacy)', null=True, upload_to='trabajos/%Y/%m/', verbose_name='Imagen (Legacy)'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='trabajos', to='trabajos.tag'),
        ),
        migrations.CreateModel(
            name='TrabajoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trabajos/%Y/%m/')),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='trabajos.trabajo')),
            ],
            options={
                'ordering': ['orden', '-id'],
            },
        ),
    ]
