# Generated by Django 5.2 on 2025-04-25 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Cantidad de dinero ingresada', max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha del ingreso')),
                ('descripcion', models.CharField(blank=True, help_text='Concepto o detalle del ingreso', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
            ],
        ),
    ]
