# Generated by Django 5.2 on 2025-06-01 19:01

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIngreso',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Cantidad de dinero ingresada', max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha del ingreso')),
                ('descripcion', models.CharField(blank=True, help_text='Concepto o detalle del ingreso', max_length=255)),
                ('creado_en', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de creación del registro')),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False, help_text='Fecha y hora de última modificación')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical ingreso',
                'verbose_name_plural': 'historical ingresos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
