# Generated by Django 5.2 on 2025-07-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0002_historicalingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalingreso',
            name='cliente',
            field=models.CharField(blank=True, help_text='Nombre del Cliente', max_length=255),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='cliente',
            field=models.CharField(blank=True, help_text='Nombre del Cliente', max_length=255),
        ),
    ]
