# Generated by Django 5.2 on 2025-07-09 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gastos.categoriagasto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gasto',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.subcategoriagasto'),
        ),
    ]
