# Generated by Django 5.2 on 2026-02-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destino', models.EmailField(help_text='Email a donde se enviarán las notificaciones de nuevos contactos.', max_length=254)),
            ],
            options={
                'verbose_name': 'Configuración de Contacto',
                'verbose_name_plural': 'Configuraciones de Contacto',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_consulta', models.CharField(choices=[('presupuesto', 'Quiero un presupuesto'), ('pedido', 'Consulta sobre un pedido'), ('info', 'Quiero info sobre servicios'), ('otro', 'Otro')], default='presupuesto', max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('respondido', models.BooleanField(default=False)),
                ('notas_internas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
